---@type Widget
local Widget = require("lapis.html").Widget

local Skill = Widget:extend(function(self)
  div({ class = "skills__skill flex-col-center gap-s" }, function()
    i({ class = "skill__icon nf " .. self.class })
    p({ class = "bold" }, self.name)
  end)
end)

return Widget:extend(function(self)
  h3("Languages")
  div({ class = "languages flex-center flex-wrap gap-m" }, function()
    widget(Skill({ class = "nf-dev-html5", name = "HTML" }))
    widget(Skill({ class = "nf-dev-css3", name = "CSS" }))
    widget(Skill({ class = "nf-fa-js", name = "Javascript" }))
    widget(Skill({ class = "nf-md-language_lua", name = "Lua" }))
    widget(Skill({ class = "nf-dev-ruby", name = "Ruby" }))
    widget(Skill({ class = "nf-dev-python", name = "Python" }))
  end)
  h3("Frameworks/libraries")
  div({ class = "frameworks-libraries flex-center flex-wrap gap-m" }, function()
    widget(Skill({ class = "nf-fa-code", name = "HTMX" }))
    widget(Skill({ class = "nf-fae-mountains", name = "Alpine.js" }))
    widget(Skill({ class = "nf-md-alpha_l_box", name = "Lapis" }))
    widget(Skill({ class = "nf-md-hat_fedora", name = "Sinatra" }))
    widget(Skill({ class = "nf-fa-react", name = "React" }))
    widget(Skill({ class = "nf-dev-django", name = "Django" }))
  end)
  h3("Tools")
  div({ class = "tools flex-center flex-wrap gap-m" }, function()
    widget(Skill({ class = "nf-dev-sass", name = "Sass" }))
    widget(Skill({ class = "nf-md-tailwind", name = "Tailwind" }))
    widget(Skill({ class = "nf-dev-sqllite", name = "Sqlite" }))
    widget(Skill({ class = "nf-dev-git", name = "Git" }))
    widget(Skill({ class = "nf-linux-tux", name = "Linux" }))
    widget(Skill({ class = "nf-fa-docker", name = "Docker" }))
  end)
end)
